spring:
  application:
    name: footbot

livescore:
  api:
    endpoint: http://livescore-api.com/api-client
    key: [taken-from-env]
    secret: [taken-from-env]

telegram:
  bot:
    name: ToparvionFootBot
    token: [taken-from-env]
    creatorId: 129560882

logging:
  level:
    org.springframework.integration: DEBUG
    org.springframework.integration.http.support.DefaultHttpHeaderMapper: INFO
    ru.toparvion.sample.footbot.telegram.FootBot: DEBUG
  pattern:
    console: '%clr(%d{${LOG_DATEFORMAT_PATTERN:yyyy-MM-dd HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}'
    dateformat: HH:mm:ss.SSS