spring:
  application:
    name: footbot
  datasource:
    url: ${JDBC_DATABASE_URL:}
    initialization-mode: always
    continue-on-error: true
  integration:
    jdbc:
      initialize-schema: always

telegram:
  bot:
    name: ToparvionFootBot
    token: [taken-from-env]
    creatorId: 129560882

sportexpress:
  broadcastUri: https://www.sport-express.ru/services/match/football/{matchId}/online/se/?json=1
  schedule:
    - id: 236351
      date: 27.06.18 19:00 Asia/Novosibirsk
      # date: 21.06.18 18:00 Europe/Moscow
      title: Россия - Египет

    - id: 236359
      date: 22.06.18 15:00 Europe/Moscow
      title: Бразилия - Коста-Рика
    - id: 236358
      date: 22.06.18 18:00 Europe/Moscow
      title: Нигерия - Исландия
    - id: 236360
      date: 22.06.18 21:00 Europe/Moscow
      title: Сербия - Швейцария

    - id: 236363
      date: 23.06.18 15:00 Europe/Moscow
      title: Бельгия - Тунис
    - id: 236362
      date: 23.06.18 18:00 Europe/Moscow
      title: Корея - Мексика
    - id: 236361
      date: 23.06.18 21:00 Europe/Moscow
      title: Германия - Швеция

    - id: 236364
      date: 24.06.18 15:00 Europe/Moscow
      title: Англия - Панама
    - id: 236366
      date: 24.06.18 18:00 Europe/Moscow
      title: Япония - Сенегал
    - id: 236365
      date: 24.06.18 21:00 Europe/Moscow
      title: Польша - Колумбия

    - id: 236367
      date: 25.06.18 17:00 Europe/Moscow
      title: Уругвай - Россия
    - id: 236370
      date: 25.06.18 21:00 Europe/Moscow
      title: Испания - Марокко

    - id: 236371
      date: 26.06.18 17:00 Europe/Moscow
      title: Дания - Франция
    - id: 236373
      date: 26.06.18 21:00 Europe/Moscow
      title: Нигерия - Аргентина

    - id: 236377
      date: 27.06.18 17:00 Europe/Moscow
      title: Корея - Германия
    - id: 236375
      date: 27.06.18 21:00 Europe/Moscow
      title: Сербия - Бразилия

    - id: 236382
      date: 28.06.18 17:00 Europe/Moscow
      title: Сенегал - Колумбия
    - id: 236379
      date: 28.06.18 21:00 Europe/Moscow
      title: Англия - Бельгия

    - id: 236384
      date: 30.06.18 17:00 Europe/Moscow
      title: Франция - Аргентина
    - id: 236383
      date: 30.06.18 21:00 Europe/Moscow
      title: Уругвай - Португалия

    - id: 236385
      date: 01.07.18 17:00 Europe/Moscow
      title: Испания - Россия
    - id: 236386
      date: 01.07.18 21:00 Europe/Moscow
      title: Хорватия - Дания

    - id: 236387
      date: 02.07.18 17:00 Europe/Moscow
      title: Бразилия - Мексика
    - id: 236388
      date: 02.07.18 21:00 Europe/Moscow
      title: Бельгия - Япония

    - id: 236389
      date: 03.07.18 17:00 Europe/Moscow
      title: Швеция - Швейцария
    - id: 236390
      date: 03.07.18 21:00 Europe/Moscow
      title: Колумбия - Англия

  # date: 21.06.18 18:00 Asia/Novosibirsk

logging:
  level:
    org.springframework.integration: INFO
    org.springframework.integration.http.support.DefaultHttpHeaderMapper: INFO
    ru.toparvion.sample.footbot: DEBUG
  pattern:
    console: '%clr(%d{${LOG_DATEFORMAT_PATTERN:yyyy-MM-dd HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}'
    dateformat: HH:mm:ss.SSS